
GET http://localhost:3001/cat


###
POST http://localhost:3001/cat
Content-Type: application/json


###
PUT http://localhost:3001/cat/1
Content-Type: application/json

{
    "id":2,
    "name": "JPT rks",
    "birthdate":"2012-12-12"
}

###
DELETE http://localhost:3001/cat/7


