
GET http://localhost:3000/user


###
POST http://localhost:3000/user
Content-Type: application/json

{
    "name":"Smiley",
    "email":"smau@smau.eu",
    "password":"pass",
    "role": 1
}

###
PUT http://localhost:3000/user/2
Content-Type: application/json

{
    "name":"Smil ura",
    "id": 1,
    "email":"smau@smau.eu",
    "password":"prss"

}

###
DELETE http://localhost:3000/user/1

